---
title: "Walkers Report – June 2, 2025"
author: "Jed Ferreras"
date: "`r Sys.Date()`"
output: html_document
---

## 📦 Load Libraries & Data

```{r setup, include=FALSE}
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(hms)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read_csv("C:/Users/jed_ferreras/PROMFI/50006-MIMMS.00/Walkers_06.03.2025.csv")
names(data)[names(data) == "walkers/10 min"] <- "walkers_10_min"

data$clock_time <- as_hms(data$time)
data$rate_per_minute <- data$walkers_10_min / 10
data$rate_per_hour <- data$walkers_10_min * 6
```


```{r}
start1 <- as_hms("09:30:00"); end1 <- as_hms("11:30:00")
start2 <- as_hms("13:30:00"); end2 <- as_hms("15:30:00")

morning <- data %>% filter(clock_time >= start1 & clock_time <= end1)
afternoon <- data %>% filter(clock_time >= start2 & clock_time <= end2)

```
```{r}
avg_morning <- mean(morning$rate_per_minute)
sd_morning <- sd(morning$rate_per_minute)
var_morning <- var(morning$rate_per_minute)

data.frame(
  "Average (people/min)" = round(avg_morning, 2),
  "Standard Deviation" = round(sd_morning, 2),
  "Variance" = round(var_morning, 2)
)

```
```{r}
avg_afternoon <- mean(afternoon$rate_per_minute)
sd_afternoon <- sd(afternoon$rate_per_minute)
var_afternoon <- var(afternoon$rate_per_minute)

data.frame(
  "Average (people/min)" = round(avg_afternoon, 2),
  "Standard Deviation" = round(sd_afternoon, 2),
  "Variance" = round(var_afternoon, 2)
)

```
```{r}
ggplot(data, aes(x = clock_time, y = rate_per_minute)) +
  geom_line(color = "steelblue", linewidth = 1) +
  geom_point(size = 2) +
  labs(
    title = "Rate of Walkers Over Time",
    subtitle = "June 2, 2025 – Measured in people per minute",
    x = "Time of Day",
    y = "People per Minute"
  ) +
  theme_minimal()

```


```{r setup, include=FALSE}
